### ISSUE TITLE
Consider allow using activerecord-import 1.x

### ISSUE THREAD

**Issue by CamilleDrapier** [kazuhisa/ken_all#67]
Thank you for providing this gem 🙇 

Would you consider allowing version 1.x of [activerecord-import](https://github.com/zdennis/activerecord-import/blob/master/CHANGELOG.md) in your gemspec please ? 🙏

It doesn't look like it would be difficult to support it from the changelog, but I do not know much about the internals of this gem... 😅

**Comment by kazuhisa** [comment]
Thanks for using my gem.
I fixed it!
